# Generated by Django 4.2.5 on 2024-01-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m183', '0003_remove_loginattempt_user_loginattempt_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
