# Generated by Django 4.2.5 on 2024-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m183', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
