# Generated by Django 4.2.5 on 2024-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m183', '0007_loginattempt_code_expires_loginattempt_sms_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
