# Generated by Django 4.2.7 on 2024-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m183', '0008_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
